version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: aura_postgres
    restart: always
    environment:
      - POSTGRES_USER=aura_user
      - POSTGRES_PASSWORD=aura_password
      - POSTGRES_DB=aura_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M # Giới hạn RAM cho DB

  ai_service:
    build: 
      context: ./aura-backend
      dockerfile: Dockerfile
    container_name: aura_ai_core
    command: python -u src/ai_service/main.py
    ports:
      - "8001:8001"
    env_file:
      - ./aura-backend/.env 
    volumes:
      - ./aura-backend/src/ai_service/ai_onnx:/app/ai_onnx
      - ./aura-backend:/app
    # Tạm thời bỏ phần GPU nếu VPS không hỗ trợ hoặc chưa cài Toolkit
    deploy:
      resources:
        limits:
          memory: 1G # Giới hạn RAM cho AI

  backend_core:
    build: 
      context: ./aura-backend
      dockerfile: Dockerfile  
    container_name: aura_backend_api
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - ai_service
    env_file:
      - ./aura-backend/.env
    environment:
      - DATABASE_URL=postgresql://aura_user:aura_password@postgres_db:5432/aura_db
      - AI_SERVICE_URL=http://aura_ai_core:8001/analyze 
      - PYTHONPATH=/app/src
    volumes:
      - ./aura-backend:/app
    deploy:
      resources:
        limits:
          memory: 1G

  frontend:
    build: ./aura-frontend
    container_name: aura_frontend
    ports:
      - "5173:5173" # Đổi cổng ra ngoài thành 80 để truy cập trực tiếp qua IP
    depends_on:
      - backend_core
    volumes:
      - ./aura-frontend:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data:
