"""add_system_config

Revision ID: 2cabbbc0b5ca
Revises: c2d030b06d68
Create Date: 2026-01-13 18:19:00.574958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cabbbc0b5ca'
down_revision: Union[str, Sequence[str], None] = 'c2d030b06d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('alert_risk_level', sa.String(), nullable=True),
    sa.Column('enable_email_alerts', sa.Boolean(), nullable=True),
    sa.Column('auto_retrain', sa.Boolean(), nullable=True),
    sa.Column('retrain_frequency_days', sa.Integer(), nullable=True),
    sa.Column('min_new_data_samples', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_configs')
    # ### end Alembic commands ###
