"""Add doctor_confirm column

Revision ID: bb75e7df6bdd
Revises: 08862080e8e2
Create Date: 2026-01-11 07:56:43.023353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb75e7df6bdd'
down_revision: Union[str, Sequence[str], None] = '08862080e8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_validations', sa.Column('doctor_confirm', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_validations', 'doctor_confirm')
    # ### end Alembic commands ###
